# Generated by Django 2.2.5 on 2019-10-17 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('video', models.URLField(blank=True, max_length=250, null=True)),
                ('content', mdeditor.fields.MDTextField(blank=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tutorial',
                'verbose_name_plural': 'tutorials',
            },
        ),
    ]
