# Generated by Django 2.2.5 on 2019-10-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20191017_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_on_homepage',
        ),
    ]
