# Generated by Django 2.2.5 on 2019-10-17 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is_correct')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_solved', models.BooleanField(blank=True, default=False, verbose_name='is_solved')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('was_tested', models.BooleanField(blank=True, default=False, verbose_name='was_tested')),
                ('is_correct', models.BooleanField(blank=True, default=False, verbose_name='is_correct')),
                ('cause', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='troubleshooting.Cause')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('inquiry', models.CharField(blank=True, max_length=100, verbose_name='query')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response')),
                ('problem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='troubleshooting.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='cause',
            name='problem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='troubleshooting.Problem'),
        ),
    ]
