# Generated by Django 2.2.5 on 2019-10-18 19:19

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='outcome',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
