# Generated by Django 2.2.5 on 2019-10-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='outcome',
            field=models.TextField(blank=True, null=True, verbose_name='outcome'),
        ),
    ]
