# Generated by Django 2.2.5 on 2019-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
                'ordering': ('created',),
            },
        ),
    ]
