# Generated by Django 2.2.12 on 2020-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200507_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='match',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
