# Generated by Django 2.2.12 on 2020-05-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200507_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='match',
        ),
    ]
