# Generated by Django 2.2.12 on 2020-05-07 23:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200501_0524'),
        ('jobs', '0007_remove_application_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3000), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('duties', models.TextField(blank=True)),
                ('professional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='accounts.Professional')),
            ],
            options={
                'verbose_name': 'work history',
                'verbose_name_plural': 'work histories',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('known_span', models.PositiveIntegerField(blank=True)),
                ('known_measure', models.CharField(blank=True, choices=[('Years', 'Years'), ('Months', 'Months')], max_length=15)),
                ('contact_info', models.CharField(blank=True, max_length=60)),
                ('reference_type', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Academic', 'Academic'), ('Social', 'Social')], max_length=15)),
                ('professional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='accounts.Professional')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('did_complete', models.BooleanField(blank=True)),
                ('certificate', models.CharField(blank=True, max_length=100)),
                ('professional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='accounts.Professional')),
            ],
            options={
                'verbose_name': 'education history',
                'verbose_name_plural': 'education histories',
            },
        ),
    ]
